version: 2
jobs:
  build:
    docker:
    - image: circleci/node:8.16.2
    steps:
    - checkout
    - run:
        name: Install dependencies
        command: yarn
    - run:
        name: Run lint
        command: yarn lint
    - run:
        name: Run prettier
        command: yarn check-format
